{
  description = "My NixOS — with Luna baked in.";

  inputs = {
    # Luna herself: the agent + dashboard + `luna` CLI + chat widget, as modules.
    luna-os.url = "github:Penguinjanator/luna-os";
    # Build against Luna's exact nixpkgs so package versions never skew.
    nixpkgs.follows = "luna-os/nixpkgs";
  };

  outputs = { nixpkgs, luna-os, ... }: {
    # Rename `my-box` to your hostname, then:
    #   sudo nixos-rebuild switch --flake .#my-box
    # Pull upstream Luna any time with: nix flake update luna-os
    nixosConfigurations.my-box = nixpkgs.lib.nixosSystem {
      system = "x86_64-linux";
      modules = [
        # ── Luna ────────────────────────────────────────────────────────────
        luna-os.nixosModules.luna       # the whole stack: agent + dashboard + CLI
        luna-os.nixosModules.kde        # her chat widget + the KDE Plasma session
        # luna-os.nixosModules.gnome    # …or GNOME instead (pick one)
        # luna-os.nixosModules.lab-kernel  # ← uncomment for the custom 7.1.0-rc7 kernel

        # ── your machine ───────────────────────────────────────────────────
        ./hardware-configuration.nix    # generated by `nixos-generate-config`
        ./goodies.nix                   # the daily-driver niceties (yours to edit)
      ];
    };
  };
}
